package campusconnect.backend.notification;

public enum NotificationType {

    EVENT_REGISTERED,
    PAYMENT_SUCCESS,
    EVENT_REMINDER,
    EVENT_CONFIRMED,
    EVENT_REJECTED,
    EVENT_PLAN_RECEIVED,

    COLLEGE_APPROVED,
    COLLEGE_REJECTED,
    COLLEGE_REGISTERED,
    EVENT_APPROVED,

    VENDOR_REGISTERED,
    VENDOR_APPROVED,
    VENDOR_REJECTED,
    VENDOR_ASSIGNED,

    FEEDBACK_REQUEST,

    STUDENT_APPROVED,
    STUDENT_REJECTED,

    STUDENT_REGISTERED,

    ADMIN_ALERT
}